### ISSUE TITLE
Author, how big is your GPU display for training this model?

### ISSUE THREAD

**Issue by smallkaka** [CSCYQJ/LOCATION-SENSITIVE-LOCAL-PROTOTYPE-NETWORK#3]
Author, how big is your GPU display for training this model?

**Comment by CSCYQJ** [comment]
I trained my model on a single NVIDIA TITAN RTX GPU of 24 GB memory.

**Comment by smallkaka** [comment]
Thank you for your reply. My single gpu is only 12GB. Can I try to change 512*512 to 256*256?
