### ISSUE TITLE
Visualization code of the final output of this network

### ISSUE THREAD

**Issue by smallkaka** [CSCYQJ/LOCATION-SENSITIVE-LOCAL-PROTOTYPE-NETWORK#4]
Hello, thank you very much for your work.I have successfully run it on my own dataset, can you tell me the visualization code of the final output of this network? Thank you so much!

**Comment by CSCYQJ** [comment]
You can first choose a support volume and some query volumes and then run the **retrieval** function in ``eval.py`` to get the corresponding segmentation mask for the given organ class. After obtaining the mask, you can plot the segmentation visualizations as you want.

**Comment by smallkaka** [comment]
OK. Thank you very much for your reply.
