### ISSUE TITLE
Environment 

### ISSUE THREAD

**Issue by smallkaka** [CSCYQJ/LOCATION-SENSITIVE-LOCAL-PROTOTYPE-NETWORK#5]
Hello!Can you tell me about the environment you trained the model in? I'm using my own environment now and it comes up with user warnings like:
"/home/su/anaconda3/envs/pyxsy/lib/python3.8/site-packages/torchvision/transforms/functional.py:417: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  warnings.warn(
/home/su/anaconda3/envs/pyxsy/lib/python3.8/site-packages/jsonpickle/ext/numpy.py:307: UserWarning: ndarray is defined by reference to an object we do not know how to serialize. A deep copy is serialized instead, breaking memory aliasing.
  warnings.warn(msg)"
These are the results I ran.
Average dice for label 1 is 0.632834289613228
Average dice for label 2 is 0.5710293556238003
Average dice for label 3 is 0.5627581559544493
Average dice for label 6 is 0.649615116232115

**Comment by CSCYQJ** [comment]
python 3.7
torch==1.6.0
torchvision==0.7.0
numpy=1.17.2

**Comment by smallkaka** [comment]
thank u!
