### ISSUE TITLE
Meaning of these numbers（likes : '29662','29663'.....）

### ISSUE THREAD

**Issue by smallkaka** [CSCYQJ/LOCATION-SENSITIVE-LOCAL-PROTOTYPE-NETWORK#7]
Hello, I want to know:
**“”num2label={'58':1,'86':2,'170':3,'30324':4,'30325':5,'187':6,'40357':7,'40358':8,'237':9,'29193':10,'1302':11,
           '1326':12,'29662':13,'29663':14,'480':15,'2473':16,'32248':17,'32249':18,'7578':19,'1247':20}“”**
What does this string of codes correspond to the data set mean, so that I can correctly correspond to my own data set. Because I can't get the data set of the paper, I can't analyze the meaning of these numbers（likes : '29662','29663'.....） by myself. Looking forward to your reply.

**Comment by CSCYQJ** [comment]
For Visceral dataset, the original GT segmentation mask files for a CT volume (e.g., 10000007) are defined by its VolumeID,
PatientID, RadlexID, LabelFusionType:
![image](https://user-images.githubusercontent.com/25661863/227689730-a70fbcfe-74cf-4fc6-883f-94f1184f560d.png)
So each number（likes : '29662','29663'.....）represents a labeled organ class for the CT volume

**Comment by smallkaka** [comment]
thank u！Does a seg.nii file include all 20 category seg masks? Or, a seg.nii file only includes one organ mask?

**Comment by CSCYQJ** [comment]
only includes one organ mask

**Comment by smallkaka** [comment]
OK.Thank u！
