### ISSUE TITLE
How the Visceral data set is organized?

### ISSUE THREAD

**Issue by Eternity16** [CSCYQJ/LOCATION-SENSITIVE-LOCAL-PROTOTYPE-NETWORK#8]
Hello, excuse me. Since I do not have access to the Visceral dataset, I am not sure how the data is organized before processing. Could you please explain how the Visceral dataset is organized and what is in each directory?

**Comment by Eternity16** [comment]
Maybe I should state my question a little more clearly:
1, Are nii original abdominal CT image files, in the folder Visceral SilverCorpus/Volume?
2, Is a nii label corresponding to a CT image of the Volume folder and all the organs have been marked out of it, in the folder Visceral SilverCorpus/segmentations  ?
3. What is the naming format of the nii files in the two directories? I'm not sure what the numbers mean in your code.

I really hope that the author can answer these three questions, which will be of great help for me to run the code

**Comment by CSCYQJ** [comment]
Maybe  **issue7** (#7 ) can help

**Comment by Eternity16** [comment]
> 

oh, yes! Thank you for your help!
